//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank_Account_Registration
    {
        public int Id { get; set; }
        public string Confirm_Type_Of_Bank_ACCOUNT { get; set; }
        public string Confrim_Type_Of_CURRENCY { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public Nullable<long> Contact_Number { get; set; }
        public string Email_Address { get; set; }
        public string Mailing_Home_Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<int> Postal_Code { get; set; }
        public string Country { get; set; }
    }
}
