//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank_Rating
    {
        public int Id { get; set; }
        public string Company_Name { get; set; }
        public string Financial_Institution_Name { get; set; }
        public string Financial_Institution_Contact_Name { get; set; }
        public string Name { get; set; }
        public string Account_In_The_name_Of_FirstName { get; set; }
        public string LastName { get; set; }
        public string Balance { get; set; }
        public string Signature { get; set; }
        public string Confirm_Bank_ACCOUNT_TYPE { get; set; }
    }
}
