//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credit_Request_form
    {
        public int Id { get; set; }
        public string Parent_Name { get; set; }
        public string PermanentAddress_Line1 { get; set; }
        public string PermanentAddress_Line2 { get; set; }
        public string PermanentAddress_Line3 { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public Nullable<int> PostalCode { get; set; }
        public string Country { get; set; }
        public string Contact_Number { get; set; }
        public string First_Participant_Name { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Activity { get; set; }
        public string Class_Code { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<int> Amount_Paid { get; set; }
        public string Reason_For_CreditRequest { get; set; }
        public byte[] Employee_Signature { get; set; }
    }
}
