//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanApplicationForm
    {
        public int id { get; set; }
        public string Desired_Loan_Amount { get; set; }
        public string Annual_Income { get; set; }
        public string Your_Name { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<long> Phone_Number { get; set; }
        public string EmailAddress { get; set; }
        public string Home_Address { get; set; }
        public string Line_2 { get; set; }
        public string Line_3 { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string Postal_Code { get; set; }
        public string Country { get; set; }
        public string Job_Title { get; set; }
        public string Employer_Name { get; set; }
        public string Confirm_Reason_Of_LOAN { get; set; }
    }
}
