//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank_Management_System.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bank_Management_SystemEntities2 : DbContext
    {
        public Bank_Management_SystemEntities2()
            : base("name=Bank_Management_SystemEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bank_Rating> Bank_Ratings { get; set; }
        public virtual DbSet<Bank_Account_Registration> Bank_Account_Registration { get; set; }
        public virtual DbSet<BankAuthorizationForm> BankAuthorizationForms { get; set; }
        public virtual DbSet<Credit_Request_form> Credit_Request_forms { get; set; }
        public virtual DbSet<Direct_Deposit_Authorization_Form> Direct_Deposit_Authorization_Form { get; set; }
        public virtual DbSet<LoanApplicationForm> LoanApplicationForms { get; set; }
    }
}
